server:
  applicationConnectors:
    - type: https
      port: 443
      keyStorePath: webauthn-demo.p12
      keyStorePassword: p@ssw0rd
      validateCerts: false
  adminConnectors:
      - type: http
        port: 8081
  rootPath: '/api/'

logging:
  level: INFO
  loggers:
    javax.ws.rs.ext.MessageBodyWriter: DEBUG
  appenders:
    - type: console
